table submissions
	lineageTag: 17eefaba-b1a3-4027-9939-d8f5651eeffc

	measure s_total_count = COUNTROWS(submissions)
		formatString: 0
		lineageTag: 2779e6ef-3998-4b64-b4aa-bb4ce3f01572

	measure s_last24h_count = ```
			
			    var counts = 
			        CALCULATE(
			                [s_total_count],
			                FILTER(
			                    submissions,
			                    submissions[time_est] > NOW() - 1
			                )
			        )
			    RETURN
			        IF(
			            counts = BLANK(),
			            0,
			            counts
			        )
			        
			```
		formatString: 0
		lineageTag: 8b753841-3567-47d9-9144-be6245601ff6

	measure s_last24h_flag = ```
			
			    IF(
			        SELECTEDVALUE(submissions[time_est]) > (NOW() - 1),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: 2a9caa38-55ec-43b4-8e1b-acbcc723633d

	measure s_last7d_flag = ```
			
			    IF(
			        SELECTEDVALUE(submissions[time_est]) > (NOW() - 7),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: f54195d7-c6a5-40ab-b4ba-b992f7229fa7

	measure s_last30d_flag = ```
			
			    IF(
			        SELECTEDVALUE(submissions[time_est]) > (NOW() - 30),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: 0077d16c-1954-44cd-b63d-db49fe31fe45

	measure s_last6m_flag = ```
			
			    IF(
			        SELECTEDVALUE(submissions[time_est]) > (NOW() - 182),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: de53eb86-b8f3-44de-86c0-0ac62cd2d014

	measure s_last1y_flag = ```
			
			    IF(
			        SELECTEDVALUE(submissions[time_est]) > (NOW() - 365),
			        1,
			        0
			    )
			```
		formatString: 0
		lineageTag: 24bafd54-a956-450d-bdc3-c67004df53e5

	measure test = DIVIDE([total_count], [s_total_count])
		formatString: #,0.00
		lineageTag: d9fa46dd-a7cb-441d-ba68-792ce4806505

	column subreddit_name
		dataType: string
		lineageTag: 84ed9b61-d4f6-4db1-a4fe-b813bceaed7b
		summarizeBy: none
		sourceColumn: subreddit_name

		annotation SummarizationSetBy = Automatic

	column key
		dataType: string
		lineageTag: a62119f8-04b9-4f1b-aa87-cecfdc383e4c
		summarizeBy: none
		sourceColumn: key

		annotation SummarizationSetBy = Automatic

	column post_title
		dataType: string
		lineageTag: 25ab0f3f-05d3-48c8-9f54-cb3e2b56af97
		summarizeBy: none
		sourceColumn: post_title

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 20eec141-e90d-4893-9a68-5376ee7908aa
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: int64
		formatString: 0
		lineageTag: f0c37889-a382-40d5-80e3-7d72e649a3f7
		summarizeBy: sum
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Self_text
		dataType: string
		lineageTag: 75d24d82-fd65-410d-8b27-27b1c70101f1
		summarizeBy: none
		sourceColumn: Self_text

		annotation SummarizationSetBy = Automatic

	column time_utc
		dataType: string
		lineageTag: 87ddc65c-a2bb-4f6c-b8b1-78b08484dd8f
		summarizeBy: none
		sourceColumn: time_utc

		annotation SummarizationSetBy = Automatic

	column upvote_ratio
		dataType: double
		lineageTag: df656cb0-33e5-48f2-ad04-097e579fe32b
		summarizeBy: sum
		sourceColumn: upvote_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column URL
		dataType: string
		lineageTag: 88f515b6-d647-4653-a9ef-447a5901801b
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column time_est
		dataType: dateTime
		formatString: General Date
		lineageTag: da9d42b6-ccf6-466a-a484-2e942cb0c8e3
		summarizeBy: none
		sourceColumn: time_est

		annotation SummarizationSetBy = Automatic

	column title_sentiment
		dataType: double
		lineageTag: e1a4dd2a-f3bd-4923-ae44-57c50bf9135e
		summarizeBy: sum
		sourceColumn: title_sentiment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition submissions = m
		mode: import
		source =
				let
				    Source = Sql.Database("myfreesqldbserver66.database.windows.net", "subcrawler"),
				    dbo_submissions = Source{[Schema="dbo",Item="submissions"]}[Data]
				in
				    dbo_submissions

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

