name: Power BI Fabric CI/CD (with BPA)

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

env:
  FABRIC_API_URL: https://api.fabric.microsoft.com

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-deploy:
    runs-on: windows-latest   # Tabular Editor requires Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Tabular Editor 2 Portable
        shell: pwsh
        run: |
          Write-Host "⬇️  Downloading Tabular Editor 2 portable..."
          $url = "https://github.com/TabularEditor/TabularEditor/releases/latest/download/TabularEditor.Portable.zip"
          Invoke-WebRequest -Uri $url -OutFile "TabularEditor.zip"
          Expand-Archive TabularEditor.zip -DestinationPath "TabularEditor"
          Write-Host "✅ Tabular Editor extracted."
          Get-ChildItem TabularEditor

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": ""
            }
          auth-type: SERVICE_PRINCIPAL
          allow-no-subscriptions: true

      - name: Get Fabric Access Token
        shell: pwsh
        run: |
          Write-Host "🔐 Fetching Fabric access token..."
          $FABRIC_TOKEN = az account get-access-token --resource "${{ env.FABRIC_API_URL }}" --query accessToken -o tsv
          Write-Host "FABRIC_TOKEN=$FABRIC_TOKEN" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Write-Host "✅ Token retrieved."

      - name: Run BPA Validation
        shell: pwsh
        run: |
          Write-Host "🔍 Running Best Practice Analyzer..."
          $ModelPath = "CCDP.SemanticModel/definition/model.tmdl"
          if (-Not (Test-Path $ModelPath)) {
              Write-Error "❌ model.tmdl not found at $ModelPath"
              exit 1
          }

          $RulesPath = "BPARules.json"
          if (-Not (Test-Path $RulesPath)) {
              Write-Error "❌ BPA rules file not found!"
              exit 1
          }

          $TEPath = "TabularEditor/TabularEditor.exe"
          Write-Host "🧠 Executing BPA via $TEPath..."
          & $TEPath -BPA $ModelPath -Rules $RulesPath -ExportResults "bpa-results.json" -IgnoreWarnings -Format JSON

          Write-Host "📊 BPA results exported to bpa-results.json"
          $results = Get-Content "bpa-results.json" | ConvertFrom-Json
          $violations = $results | Where-Object { $_.Severity -eq "Error" -or $_.Severity -eq "Warning" }

          if ($violations.Count -gt 0) {
              Write-Host "❌ BPA found $($violations.Count) issues:"
              $violations | ForEach-Object { Write-Host " - Rule: $($_.RuleId) | $($_.Message)" }
              exit 1
          } else {
              Write-Host "✅ BPA validation passed."
          }

      - name: Publish PBIP to Fabric Workspace
        if: success()
        shell: pwsh
        env:
          WORKSPACE_ID: ${{ vars.DEV_WORKSPACE_ID }}
          FABRIC_TOKEN: ${{ env.FABRIC_TOKEN }}
        run: |
          Write-Host "🚀 Publishing CCDP.pbip to Fabric workspace $WORKSPACE_ID..."
          if (-Not (Test-Path "CCDP.pbip")) {
              Write-Error "❌ CCDP.pbip not found!"
              exit 1
          }

          $Response = curl -s -w "`n%{http_code}" -X POST `
            "${{ env.FABRIC_API_URL }}/v1/workspaces/$WORKSPACE_ID/files" `
            -H "Authorization: Bearer $FABRIC_TOKEN" `
            -F "file=@CCDP.pbip" `
            -F "overwrite=true" `
            -F "displayName=CCDP.pbip"

          $HTTP_BODY = $Response -split "`n" | Select-Object -First ($Response.Length - 1)
          $HTTP_CODE = $Response -split "`n" | Select-Object -Last 1
          Write-Host "Response code: $HTTP_CODE"
          Write-Host "Response body: $HTTP_BODY"

          if ([int]$HTTP_CODE -ge 200 -and [int]$HTTP_CODE -lt 300) {
              Write-Host "✅ CCDP.pbip published successfully."
          } else {
              Write-Error "❌ Publish failed with HTTP $HTTP_CODE"
              exit 1
          }
