name: Power BI Fabric CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

env:
  FABRIC_API_URL: https://api.fabric.microsoft.com
  PBIP_DIR: ${{ vars.PBIP_DIR || '.' }} # Use repository root as fallback if PBIP_DIR is not set

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": ""
            }
          auth-type: SERVICE_PRINCIPAL
          allow-no-subscriptions: true

      - name: Get Fabric Access Token
        id: get-token
        run: |
          FABRIC_TOKEN=$(az account get-access-token --resource "${{ env.FABRIC_API_URL }}" --query accessToken -o tsv)
          echo "FABRIC_TOKEN=$FABRIC_TOKEN" >> $GITHUB_ENV
        continue-on-error: false

      - name: Run BPA Checks
        run: |
          echo "Running Power BI Best Practices Analyzer checks..."
          # Check if .pbip files exist
          PBIP_FILES=$(find "${{ env.PBIP_DIR }}" -type d -name "*.pbip" 2>/dev/null)
          if [ -z "$PBIP_FILES" ]; then
            echo "Error: No .pbip files found in ${{ env.PBIP_DIR }}"
            echo "Please set the PBIP_DIR variable in GitHub repository settings or ensure .pbip files exist."
            exit 1
          fi
          # Initialize flag for validation errors
          VALIDATION_FAILED=false
          # Check for '/' in measures
          while IFS= read -r pbip; do
            if [ -d "$pbip" ]; then
              echo "Checking $pbip for BPA compliance..."
              # Extract measures and check for '/' in DAX expressions
              INVALID_MEASURES=$(find "$pbip" -type f -name "*.json" -exec grep -l '"type": "measure"' {} \; | while read -r file; do
                grep -B1 '"type": "measure"' "$file" | grep -Po '"Expression"\s*:\s*"\K[^"]+' | grep -E '[^A-Z0-9_/ ]/[ ]*[^A-Z0-9_/ ]' && echo " (in $file)" || true
              done)
              if [ ! -z "$INVALID_MEASURES" ]; then
                echo "Error: Found measures using '/' instead of DIVIDE() in $pbip:"
                echo "$INVALID_MEASURES"
                VALIDATION_FAILED=true
              fi
              # Additional BPA checks
              # Check for unused columns
              UNUSED_COLUMNS=$(grep -r '"isHidden": true' "$pbip/Model" || true)
              if [ ! -z "$UNUSED_COLUMNS" ]; then
                echo "Warning: Found hidden columns in $pbip that might be unused:"
                echo "$UNUSED_COLUMNS"
              fi
              # Check for high cardinality columns
              if grep -r '"type": "table"' "$pbip/Model" | grep -q '"cardinality": "high"'; then
                echo "Warning: High cardinality columns detected in $pbip"
              fi
            fi
          done <<< "$PBIP_FILES"
          if [ "$VALIDATION_FAILED" = true ]; then
            echo "Error: BPA validation failed due to invalid measures."
            exit 1
          fi
          echo "BPA checks completed successfully."

      - name: Publish PBIP to Fabric Workspace
        env:
          WORKSPACE_ID: ${{ github.ref_name == 'main' && vars.PROD_WORKSPACE_ID || vars.DEV_WORKSPACE_ID }}
          FABRIC_TOKEN: ${{ env.FABRIC_TOKEN }}
        run: |
          echo "Publishing .pbip files to Fabric workspace $WORKSPACE_ID..."
          while IFS= read -r pbip; do
            if [ -d "$pbip" ]; then
              pbip_name=$(basename "$pbip")
              echo "Processing $pbip_name..."
              zip -r "${pbip_name}.zip" "$pbip"
              curl -X POST \
                "${{ env.FABRIC_API_URL }}/v1/workspaces/$WORKSPACE_ID/files" \
                -H "Authorization: Bearer $FABRIC_TOKEN" \
                -F "file=@${pbip_name}.zip" \
                -F "overwrite=true" \
                -F "displayName=$pbip_name" \
                || { echo "Error: Failed to publish $pbip_name"; exit 1; }
              rm "${pbip_name}.zip"
            fi
          done <<< "$(find "${{ env.PBIP_DIR }}" -type d -name "*.pbip" 2>/dev/null)"
          echo "All .pbip files published successfully."
