name: Test Fabric API

on:
  push:
    branches: [ "*" ]  # Triggers on push to any branch

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Authenticate to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Get Fabric Access Token
      id: token
      run: |
        token=$(az account get-access-token --resource https://api.fabric.microsoft.com --query accessToken -o tsv)
        echo "FABRIC_TOKEN=$token" >> $GITHUB_ENV

    - name: Check Git Status
      env:
        WORKSPACE_ID: ${{ vars.DEV_WORKSPACE_ID }}
      run: |
        STATUS_RESPONSE=$(curl -X GET \
          "https://api.fabric.microsoft.com/v1/workspaces/$WORKSPACE_ID/git/status" \
          -H "Authorization: Bearer $FABRIC_TOKEN" \
          -H "Content-Type: application/json")
        echo "Git Status: $STATUS_RESPONSE"
