name: Power BI Fabric CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

env:
  FABRIC_API_URL: https://api.fabric.microsoft.com

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": ""
            }
          auth-type: SERVICE_PRINCIPAL
          allow-no-subscriptions: true

      - name: Get Fabric Access Token
        id: get-token
        run: |
          echo "🔐 Fetching Fabric access token..."
          FABRIC_TOKEN=$(az account get-access-token --resource "${{ env.FABRIC_API_URL }}" --query accessToken -o tsv)
          echo "FABRIC_TOKEN=$FABRIC_TOKEN" >> $GITHUB_ENV
          echo "✅ Token retrieved."

      - name: Validate DIVIDE usage in measures (TMDL)
        run: |
          echo "🔍 Validating DAX measures for correct DIVIDE() usage..."
          if [ ! -f "CCDP.SemanticModel/model.tmdl" ]; then
            echo "❌ Error: model.tmdl not found at CCDP.SemanticModel/model.tmdl"
            exit 1
          fi
          INVALID_MEASURES=$(grep -E 'measure .*=' CCDP.SemanticModel/model.tmdl | grep '/')
          if [ ! -z "$INVALID_MEASURES" ]; then
            echo "❌ Found measures using '/' instead of DIVIDE():"
            echo "$INVALID_MEASURES"
            exit 1
          fi
          echo "✅ All measures correctly use DIVIDE()."

      - name: Publish PBIP to Fabric Workspace
        env:
          WORKSPACE_ID: ${{ vars.DEV_WORKSPACE_ID }}
          FABRIC_TOKEN: ${{ env.FABRIC_TOKEN }}
        run: |
          echo "🚀 Publishing CCDP.pbip to Fabric workspace $WORKSPACE_ID..."
          curl -X POST \
            "${{ env.FABRIC_API_URL }}/v1/workspaces/$WORKSPACE_ID/files" \
            -H "Authorization: Bearer $FABRIC_TOKEN" \
            -F "file=@CCDP.pbip" \
            -F "overwrite=true" \
            -F "displayName=CCDP.pbip" \
            || { echo "❌ Error: Failed to publish CCDP.pbip"; exit 1; }
          echo "✅ CCDP.pbip published successfully."
